# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::BaseController`.
# Please instead update this file by running `bin/tapioca dsl Api::BaseController`.


class Api::BaseController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
