default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_0900_ai_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host:     <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port:     <%= ENV.fetch("DB_PORT") { 3306 } %>
  variables:
    sql_mode: "STRICT_ALL_TABLES"

development:
  primary:
    <<: *default
    database: csv_bulk_importer_development
  cache:
    <<: *default
    database: csv_bulk_importer_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: csv_bulk_importer_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: csv_bulk_importer_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: csv_bulk_importer_test
  cache:
    <<: *default
    database: csv_bulk_importer_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: csv_bulk_importer_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: csv_bulk_importer_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "csv_bulk_importer") %>
    username: <%= ENV.fetch("DATABASE_USERNAME") { ENV.fetch("DB_USERNAME", "admin") } %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") { ENV.fetch("DB_PASSWORD", "") } %>
    host: <%= ENV.fetch("DATABASE_HOST") { ENV.fetch("DB_HOST", "127.0.0.1") } %>
    port: <%= ENV.fetch("DATABASE_PORT") { ENV.fetch("DB_PORT", 3306) } %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME", "csv_bulk_importer") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME", "csv_bulk_importer") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_NAME", "csv_bulk_importer") %>_cable
    migrations_paths: db/cable_migrate
